services:
  claude-code:
    build: .
    volumes:
      - ./storage/work:/work
      - ./storage/cache:/home/claude/.cache
      - ./storage/start.sh:/home/claude/start.sh
      - ./storage/claude:/home/claude/.claude
    working_dir: /work
    stdin_open: true
    tty: true
    environment:
      - OPENAI_API_URL=${OPENAI_API_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-none}
      - OPENAI_API_MODEL=${OPENAI_API_MODEL}
      - BUN_INSTALL_CACHE_DIR=/root/.cache/bun-cache
